name: overlay_tutorial
version: 3.0.0
description: A Flutter package for displaying overlay tutorial by cutting a hole on widget. It allows also to add hint aside the hole.
repository: https://github.com/TabooSun/overlay_tutorial
environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  async: ^2.5.0
  equatable: ^2.0.3
dev_dependencies:
  pedantic: ^1.11.1
  taboosun_lints:
    git:
      url: https://github.com/TabooSun/dart_taboosun_lints.git
      ref: v1.0.1
  flutter_test:
    sdk: flutter
flutter: null
