name: Flutter CI
on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
  workflow_dispatch:
    
env:
  FLUTTER_VERSION: stable

jobs:
  Validate-format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: $FLUTTER_VERSION

      - name: Check Dart code style
        run: flutter format . --set-exit-if-changed

  Analyze-code:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: $FLUTTER_VERSION

      - name: Get Pub packages
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

  Run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: $FLUTTER_VERSION

      - name: Run test
        run: flutter test